### ISSUE TITLE
Crashes When trying to like comic

### ISSUE THREAD

**Issue by ZusorCode** [T-Rex96/Easy_xkcd#122]
Every time I'm trying to like a comic the app force closes. Running Oreo on a OnePlus 5 (Stock OxygenOS)

**Comment by I-Al-Istannen** [comment]
I can reproduce the error. It seems like the highest comic stored in the preference file goes out of sync with the realm database (1990 vs 1645). 

Any attempt to save a comic that is higher to the favourites leads to a NPE here:
```java
RealmComic comic = realm.where(RealmComic.class).equalTo("comicNumber", fav).findFirst();
/* >> */ comic.setFavorite(isFav);
```
as the comic is null.

**Additionally** for me a comic with the id `0` exists, making it impossible to add any new comics to the database due to what is outline [here](https://stackoverflow.com/questions/30162473/primary-key-constraint-broken-value-already-exists-0#30167774).

I do not know whether the two bugs are related. Purging the comic with id `0` (it only contains null data) and manually setting the highest comic in the preference file to 1645 resolves the errors.

**Comment by T-Rex96** [comment]
The possible cause should be fixed in the upcoming release, as I'm switiching to a purely Realm-based database. I'll also include a fix for the second bug, i.e. replace calls to `Realm.createObject` with `copyToRealmOrUpdate()`

**Comment by T-Rex96** [comment]
The update went live on Google Play today, hope that fixed both bugs

**Comment by ZusorCode** [comment]
Thanks a ton, that fixed it!
