### ISSUE TITLE
Black bar in bottom area on every comic

### ISSUE THREAD

**Issue by ZusorCode** [T-Rex96/Easy_xkcd#123]
An example: https://i.imgur.com/j4mQZih.jpg

Using Android Oreo on OxygenOS 5.0/OnePlus 5

**Comment by T-Rex96** [comment]
Well that's a weird one, reinstalling doesn't fix it?

**Comment by ZusorCode** [comment]
Nope, reinstalled it, still doesn't work. If you want some more diagnostic data or want me to try something just tell me.

**Comment by T-Rex96** [comment]
Does this still happen when you enable offline mode?

**Comment by ZusorCode** [comment]
Oh sorry, I didn't mention that. It only happens on offline mode. With offline mode images look fine

**Comment by T-Rex96** [comment]
Ah ok that's interesting, but I'm afraid I probably won't be able to fix it

**Comment by ZusorCode** [comment]
Where are the images usually stored? I could look if the images are ok outside of the app.

**Comment by T-Rex96** [comment]
The folder is just called easy xkcd

**Comment by not-inept** [comment]
I also see this, I didn't notice at first with the night theme. I have a Galaxy S8 on Android 8.0 (Oreo) and this only happens in offline mode. Reloading the database/etc doesn't help with the issue.

I don't see an easy xkcd folder on my SD card. Looking at the app's usage, I can see it is using ~200mb of storage however there isn't a clear way to access it. I tried setting a custom path, and while I can see the folder it appears to be empty. (This is from using a file browser on my phone).

I can try debugging it later, quickly googling indicates adb might reveal the contents of the folder to at least prove/disprove if the problem is with the files.

**Comment by not-inept** [comment]
I also see this on Android 9.0 (on the S8, just updated today finally). When running in the debugger it seems to fail saving to the sd card (which would explain the missing folder) and saves/loads from internal storage. The bitmaps being saved appear to have the black regions. A brief googling leaves me with the impression that these black bars are what happens when the dimensions of the bitmap are different the contents. In this case, it's cutting off the comic, so I think we might either be improperly storing the files in internal storage.

**Comment by not-inept** [comment]
I got a chance to take another look a few minutes ago, from local testing this seems to resolve the issue.
