### ISSUE TITLE
Enhancement - Setting directory for offline downloads

### ISSUE THREAD

**Issue by luigibai** [T-Rex96/Easy_xkcd#6]
I prefer to download the offline entries to my external SDCARD because it has much more room than the internal storage.
The directory for offline storage could be a configuration setting.

**Comment by T-Rex96** [comment]
Looking into it.

**Comment by luigibai** [comment]
See, e.g., https://github.com/smarek/Simple-Dilbert/search?utf8=%E2%9C%93&q=download

**Comment by T-Rex96** [comment]
Haha this app seems to do it's job really good :)

**Comment by T-Rex96** [comment]
Hey, I've compiled an experimental version which should save images to sd card when adding favorites (saving offline images to sd card would be implemented later, if this works). Since I do not own a device with sc card, could you try out the app and see if it works for you?

https://www.dropbox.com/s/wxmw3q2yhm3zjxy/EasyXkcd%20external%20storage.apk?dl=0

**Comment by T-Rex96** [comment]
External storage is now standard for saving images

**Comment by luigibai** [comment]
Thank you!
