### ISSUE TITLE
High memory usage causes OutOfMemoryError

### ISSUE THREAD

**Issue by tom-heimbrodt** [T-Rex96/Easy_xkcd#8]
Because the app crashes occasionally on my phone, I did some researches with Android Studio:
When using the app (and swiping through the comics) the memory usage increases and increases . . .
When it reaches ca. 55 MB an OutOfMemoryError is thrown.
Also it seems like all favourites are loaded into Memory, which isn't a perfect behaviour when there are a number of favourites . . .
Maybee it's possible to unload more comics that are not needed any more and don't load all favourites into RAM?

**Comment by tom-heimbrodt** [comment]
Did anybody else experienced such crashes?
Can't realy explain that, because my system is telling me there is at least 200 MB free RAM. 
Might be some Android related stuff?

**Comment by T-Rex96** [comment]
On my secondary device with offline mode disabled the memory usage will always be around 30MB, so it seems to be an issue with offline mode...

**Comment by T-Rex96** [comment]
Yep, it is definitely caused by offline mode. The OfflineComic objects hold a direct reference to the comic image. The method getBitmap() returns this image. Instead the offline comic should just return a reference to the bitmap but not hold a reference itself, so that the bitmap can be garbage collected.
